### ISSUE TITLE
One-Click Install on OS2008 Broken

### ISSUE THREAD

**Issue by Pharcsa** [aarddict/desktop#12]
Using the Install file off of arddict homepage, after adding arddict repository and extras-devel, getting error - unable to install aarddict Application Package Not Found

Broken Install off of Maemo Downloads - OS2008

**Comment by itkach** [comment]
In Aard Dictionary catalog details, Web address should be _http://aarddict.org/maemo_ instead of _http://aarddict.github.org/maemo_. I updated [maemo.install](http://github.com/downloads/aarddict/desktop/maemo.install), give it a try.

**Comment by Pharcsa** [comment]
maemo.install fixed and installing correctly on OS2008. Thank you!
