### ISSUE TITLE
Recurring requests for network connection in offline mode on N900

### ISSUE THREAD

**Issue by ortylp** [aarddict/desktop#13]
While the N900 is offline (disabled or inaccessible network connection) there are Maemo requesters coming with question about establishing Internet connection.

These requests come many times while browsing found entries. As such makes reading offline wikipedia entries pretty annoying...

**Comment by itkach** [comment]
Aard Dictionary does not attempt to establish internet connection - ever. It does open browser when an external link is clicked, and the browser will ask if you want to exit offline mode though - it that what you find annoying? External links look different from internal links (icon next to it and, when using Aard article appearance style instead of Wikipedia style, different color), so it should be fairly easy to avoid clicking them if you don't want to go online.

**Comment by ortylp** [comment]
"Aard Dictionary does not attempt to establish internet connection - ever."

It is exactly what I would assume, but...

It looks like this:
1. Go to offline mode
2. Start aarddict (tap on the icon on the desktop)
3. Dictionaries are loaded (seven of those, all from aarddict.org: wikipedias en/de/pl, some dictionaries)
4. Last query gets executed (example I tested at the moment there was "goat" as a search term)
5. Without touching anything on the screen or keyboard since tapping aarddict icon from the N900 desktop there comes requester with "Exit offline mode?" and buttons Yes/No (a standard Maemo requester in case an application wants to establish internet connection).

I started aardict with strace
strace -f -o aarddict.log aarddict

grep -E " socket| connect" aarddict.log
1934  socket(PF_FILE, SOCK_STREAM, 0)   = 5
1934  connect(5, {sa_family=AF_FILE, path="/var/run/dbus/system_bus_socket"}, 33) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 5
1932  connect(5, {sa_family=AF_FILE, path="/var/run/dbus/system_bus_socket"}, 33) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 8
1932  connect(8, {sa_family=AF_FILE, path=@"/tmp/.X11-unix/X0"}, 20) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 9
1932  connect(9, {sa_family=AF_FILE, path=@"/tmp/.X11-unix/X0"}, 20) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 11
1932  connect(11, {sa_family=AF_FILE, path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 11
1932  connect(11, {sa_family=AF_FILE, path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 10
1932  connect(10, {sa_family=AF_FILE, path=@"/var/tmp/sapwood-:0.0"}, 110) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 11
1932  connect(11, {sa_family=AF_FILE, path=@"/tmp/dbus-SXS1ApKKyv"}, 23) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 12
1932  connect(12, {sa_family=AF_FILE, path="/var/run/dbus/system_bus_socket"}, 33) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 13
1932  connect(13, {sa_family=AF_FILE, path="/var/run/dbus/system_bus_socket"}, 33) = 0
1932  socket(PF_FILE, SOCK_STREAM, 0)   = 13
1932  connect(13, {sa_family=AF_FILE, path="/var/run/dbus/system_bus_socket"}, 33) = 0

One of these must have triggered the network connection, but all of these refer to PF_FILE.

Bug in Maemo? Any other Ideas?

**Comment by ortylp** [comment]
I have further info:

The problematic call is:

view.page().currentFrame().setHtml(article.text, QUrl(view.title))
in article_loaded()

Commenting the line out stops Maemo requester from appearing, but renders the application useless.

Other test shows, that "goat" from wordnet (text entries) does not trigger the requester, the goat from English wikipedia does.

Looks like Maemo bug, but is there anything in html entries, that could trigger WebKit to think that network connection is required?

**Comment by itkach** [comment]
Interesting observations, thank you. This does appear to be Maemo 5 specific behavior - doesn't happen for me on N810 with Diablo.

I wonder if this is triggered by [setHtml()](http://doc.qt.nokia.com/4.6/qwebview.html#setHtml) loading "external" resources. Now, article html does not include any external resources, however it does embed some images using [data URI scheme](http://en.wikipedia.org/wiki/Data_URI_scheme) - math, external link marker, also list bullets when using Wikipedia style. I guess this may appear as a network request and trigger "Exit offline mode" prompt if not properly handled.

I've put together a test app: https://gist.github.com/666758 , can you please run it on N900 when in offline mode and see if you get the prompt? 
Run with html sample that contains embedded image:
    python test_data_scheme.py 1
Run with html sample that contains only text:
    python test_data_scheme.py 2

**Comment by ortylp** [comment]
python test_data_scheme.py 1
Triggers "Exit offline mode"
python test_data_scheme.py 2
does not.

BTW: N900 has Qt 4.7 already with PR 1.3

**Comment by itkach** [comment]
Aha, so it's data URI. Looks like a Maemo bug. Is this with Qt 4.6/PR1.2 or QT 4.7/PR1.3 or both?

**Comment by ortylp** [comment]
With Qt 4.7/PR1.3, I have only one N900 and still in single-boot. Maybe after Dublin next week it will change, but it is still my main phone and it has to work properly :)

This requester for online mode comes also if you use QNetworkManager and try to retrieve URL in CacheOnly mode...  I had to implement cache'ing myself to get rid of this message box popping up without reason.

**Comment by itkach** [comment]
Closing the issue since this needs to be fixed in Maemo instead.
