### ISSUE TITLE
Text set to black, but background left at default == black on black

### ISSUE THREAD

**Issue by GreenReaper** [aarddict/desktop#20]
On my N800 tablet, the styles are set so that text is white and the background is black. Unfortunately Aard Dictionary appears to force text to be black, while leaving the background colour as the default. This means that all I see is a handful of blue links in a sea of blackness, perhaps with a "Redirected from X" visible at the top (since that has a set background colour).

At a minimum Aard Dictionary should either force both text and background colours to a particular colour or leave them both at the system defaults, because otherwise it risks not being readable. Being able to set the background and text colours in the same way that you can standard colours would also be neat, given that others could be set through HTML styles in the page itself.

**Comment by itkach** [comment]
You can tweak css as described in http://aarddict.org/aarddict/doc/aarddict.html#article-appearance to change text color.

**Comment by GreenReaper** [comment]
That's great, and I can probably work around the problem with that - but if text on my device is white everywhere else, it probably shouldn't be black in the viewer. It seems like that is being set somewhere by the software.

**Comment by itkach** [comment]
No, I don't think text color is explicitly set anywhere in the code. It's possible that it's set somewhere in Wikipededia's css (didn't look too closely at it, can't be sure) - what happens when you turn off Wikipedia style, is the text still not system color? It can also be coming from WebKit's default style or maybe it's result of Qt having no real integration with the system in Maemo 4.x.

**Comment by GreenReaper** [comment]
Whether I have Wikipedia style on or not, the text is the same colour. Setting body {background:white} in the CSS override makes it visible.

The text in the panel on the right of the "Dictionary Info" dialog is also black on a black background. Perhaps QT is making an assumption . . .
