### ISSUE TITLE
Convert bz2 ---> aar using windows

### ISSUE THREAD

**Issue by yeymen** [aarddict/desktop#21]
Is possible convert eswiki-latest-pages-articles.xml.bz2 --->aar using windows? Thanks.

**Comment by itkach** [comment]
It is probably possible in theory, but trying to get it to work is probably going to be excruciatingly painful and not guaranteed to succeed. [All the required software](http://aarddict.org/aardtools/doc/aardtools.html#installation) needs to be installed, most of it probably has to be built from source, all the dependencies need to be tracked down and installed too. eswiki is quite big, so you have to do it all on 64-bit system, don't bother trying on 32-bit, it won't work.

**Comment by yeymen** [comment]
It seems too complicated for me. Can you update the eswiki?

Thanks in advance.

note: in the android version is missing the option to search within the article, copy text and exit...

Thanks again.
