### ISSUE TITLE
Aarddict loses position when returning in articles

### ISSUE THREAD

**Issue by rtega** [aarddict/desktop#22]
When returning to a previous article in wikipedia Aarddict loses position. This is very annoying when reading long articles and wanting to read a link somewhere. Upon turning back one has to search one's last position one's again.

**Comment by itkach** [comment]
Doesn't happen for me, position is preserved just fine. Does it happen for you on all articles or only some? What's your OS?

**Comment by rtega** [comment]
I think on all of them. I'm using Jellybean 4.1

**Comment by itkach** [comment]
I see. This is issue tracker for desktop version of Aard Dictionary, so I'm moving it there: aarddict/android#49. I didn't have a chance to test aarddict on JellyBean yet.

**Comment by rtega** [comment]
Ouch, sorry for posting in the wrong section. I didn't notice.
