### ISSUE TITLE
which the suitable for me  

### ISSUE THREAD

**Issue by hakada** [aarddict/desktop#23]
i haven't much more space in my hard disk to download all Wikipedia dictionary  volumes so i want only one volume that have the content which  related to my study field which is 'computer science engineering'  .

you can consider it as suggestion : you can give a description (categorize) for any multi-volumed dictionary 
example : volume-i Wikipedia's contents are science, history, politic ,sport .,.. etc 
,.

**Comment by itkach** [comment]
Dictionary format and volumes was designed with this use case in mind. It's really up to dictionary compiler to decide how exactly articles should be split  between volumes. Currently there's only one implementation - by size, start a new volume once maximum size is reached. Other implementations are possible. Generating volumes by top-level wikipedia categories would be nice.

**Comment by hakada** [comment]
but i think that data isn't randomly scattered inside the .aar file .. may be the split process performed according to size , ,, and at the same time the related categories are most probable  contiguous  (no contradiction here! . . why not?) .

**Comment by itkach** [comment]
No, that's not how it works at all. Article titles are sorted according to unicode default collation and added to volumes in that order, which has nothing to do wikipedia categories.
