### ISSUE TITLE
aard-tools: Compiler option from Babylon (.BGL) and/or Compressed StarDict (.dict.dz, .ifo) dictionaries with Aard Tools?

### ISSUE THREAD

**Issue by TheLinuxKitten** [aarddict/desktop#24]
I would use the dictionary arrdict in an eBook reader with CoolReader 3, I've compiled the wiki and Spanish Wikt with Aard-tools.
I have several encyclopedic dictionaries for Babylon PC program but I can not compile with Aard-tools. With stardict-editor I can convert to Compressed StarDict: res/, .ifo, .dict.dz, .idx, .syn.
Can compile Babylon dictionaries and/or Compressed StarDict dictionaries?

thanks

**Comment by itkach** [comment]
Neither babylon nor stardict dictionaries can be used as a source for aardc at the moment. New converter modules of course can be developed for aard compiler to support new source formats, feel free to contribute :)

**Comment by itkach** [comment]
Note that many dictionaries [are available in XDXF format](http://sourceforge.net/projects/xdxf/files/dicts-XDXF/), which can be converted to aard format. http://aarddict.org/dictionaries/ doesn't provide the ready-to-use downloads since it is not clear if licenses of these dictionaries allow such distribution.

**Comment by TheLinuxKitten** [comment]
Thanks!

---

 De: itkach notifications@github.com
Para: aarddict/desktop desktop@noreply.github.com 
CC: TheLinuxKitten pocholin_bordiu@yahoo.es 
Enviado: Martes 25 de diciembre de 2012 18:08
Asunto: Re: [desktop] aard-tools: Compiler option from Babylon (.BGL) and/or Compressed StarDict (.dict.dz, .ifo) dictionaries with Aard Tools? (#24)

Note that many dictionaries are available in XDXF format, which can be converted to aard format. http://aarddict.org/dictionaries/ doesn't provide the ready-to-use downloads since it is not clear if licenses of these dictionaries allow such distribution.

**Comment by ildar** [comment]
This info is _very_ useful and should be noted at [this page](http://aarddict.org/dictionaries/index.html).

**Comment by itkach** [comment]
It is noted in the _Do It Yourself_ section of the said page, not sure what else would you like to see there.

**Comment by ildar** [comment]
You're right. I was just confused when couldn't find an English-Russian
dictionary for quite some time... Sorry for the noise.
