### ISSUE TITLE
problem when compiling wiktionary

### ISSUE THREAD

**Issue by microspace** [aarddict/desktop#26]
Hello 
OS: Ubuntu 12.04 i386
After compiling tr.wikrionary.org there are no word definitions in articles, only information like language, tense, etc.
Example:
Original article:

> ffordd
> Galce
> Ad
>  Anlamlar
> [1] yol

My case (from aarddict):

> ffordd
> Galce
> Ad

as you see, there is no translation 
I've followed instructions here http://aarddict.org/aardtools/doc/aardtools.html, except that 
1) installed libicu48 instead of libicu38
2) had to give  executable permission to env-aard/bin/activate
3) simplewiki-20101026-pages-articles.cdb is not a file, but a folder
4) had lots of these messages during aardc wiki ... execution:

```
.../env-aard/local/lib/python2.7/site-packages/aardtools/mwaardhtmlwriter.py:356: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  not (element.getchildren() or element.text or element.tail) and parent):
```

thank you

**Comment by itkach** [comment]
@microspace this is issue tracker for desktop version of aarddictionary, moving issue to aarddict/tools#24
