### ISSUE TITLE
 Aard dict cannot add dictionary from micro sd

### ISSUE THREAD

**Issue by jabralburai** [aarddict/desktop#27]
hello there,
i have galaxy s2 and I have bought a new sd only for aard dictionary in order to copy the whole wiki. but the problem is that aard dic. cannot add dictionry from micro sd, however it does when copying the files to the internal memory of the mobile. PLz help me quickly! i'm lost

**Comment by itkach** [comment]
Please make sure that sd card is not defective, properly inserted and is detected by the device, dictionary files (*.aar) are fully copied, are not in a hidden directory and also watch for error messages when scanning devices for dictionaries - app shows brief message for every .aar file it found but couldn't open.

This is issue tracker of Aard Dictionary for desktop, Android version issue tracker is here: https://github.com/aarddict/android/issues.
