### ISSUE TITLE
[FR] change config dir path to XDG-proposed `$HOME/.config/$NAME`

### ISSUE THREAD

**Issue by ildar** [aarddict/desktop#28]
It is now `$HOME/.$NAME`
Please don't forget to move current configurations from the old location.

**Comment by itkach** [comment]
why? what's XDG?

**Comment by ildar** [comment]
According to
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html ,
config files for applications move to $HOME/.config/APPNAME . Most
developing applications follow this trend

**Comment by itkach** [comment]
Well, this application is not really developing all that much at the moment. Also, I'm not sure how much bearing freedesktop.org should have on Windows and Mac OS X which are among the platforms where this application runs. And last, but not least, there's non-zero work to be done for approximately zero benefit. So probably not going to happen.

**Comment by ildar** [comment]
Agreed. This was a minor and optional feature.
