### ISSUE TITLE
aarddict cli?

### ISSUE THREAD

**Issue by guaka** [aarddict/desktop#35]
related to #34 

I wanted to mention aarddict [on superuser.com](http://superuser.com/q/719720/167657) but I'm not sure how to use aarddict on the console.

**Comment by itkach** [comment]
> not sure how to use aarddict on the console

aarddict is not designed to be used on the console. It's not difficult to wrap [dictionary.py](https://github.com/aarddict/desktop/blob/c5818c27270b14a1fc1923204c6e01cfb66fcf20/aarddict/dictionary.py) in a command line utility to do lookups and retrieve content, but so far nobody asked for this and at this point this is unlikely to happen. 

[Next-gen aarddict - aard2](https://github.com/itkach/aard2-android) relies on an embedded web server to serve content, so usage similar to Kiwix example in the accepted answer is possible.
