### ISSUE TITLE
farsi dictonary

### ISSUE THREAD

**Issue by ali-libre** [aarddict/desktop#37]
Hi
Farsi dictionary link are broken ...
Pls fix it....

**Comment by itkach** [comment]
Do you mean fawiki link at http://aarddict.org? Why do you say it's broken? It's a bittorrent [magnet link](https://en.wikipedia.org/wiki/Magnet_URI_scheme), you need a bittorrent client such as [μTorrent](https://www.utorrent.com) or [QBittorrent](http://qbittorrent.org/). The link works fine for me with [Transmission](http://www.transmissionbt.com/).

**Comment by ali-libre** [comment]
Yes...sorry...i'm just tried online converters...
Thank's
